### ISSUE TITLE
Identity

### ISSUE THREAD

**Issue by lpww** [noffle/p2p-handbook#2]
Hi, I'm particularly interested in reading more about identity in p2p networks. I would appreciate it if you could expand that section :)

**Comment by hackergrrl** [comment]
Thanks for the kick in the pants! I wrote a bit [on identity](https://github.com/noffle/p2p-handbook#identity).

**Comment by lpww** [comment]
This is exactly what I was hoping for! A valuable addition to the handbook, thanks @noffle 👍

**Comment by caiogondim** [comment]
Wow. That's awesome! 
Thanks for that, @noffle
